const KEY='marketing-club-v2';
const fresh=()=>({members:seed.map((m,i)=>({...m,company:['Студия «Смысл»','Кофейня «Утро»','Независимый специалист','Web Lab','Контент-бюро','Frame Studio'][i],membership:'active',birth:'',phone:'',social:'',referral:'',photo:`assets/avatars/member-${m.id}.jpg`,paidUntil:'2027-04-05'})),notices:[{id:1,memberId:2,reason:'Три сообщения подряд',date:'2026-10-02',kind:'warning',amount:0},{id:2,memberId:5,reason:'Публикация не по теме клуба',date:'2026-10-03',kind:'warning',amount:0}],payments:[],audit:[]});
let db;try{db=JSON.parse(localStorage.getItem(KEY))||fresh();if(!Array.isArray(db.members)||!Array.isArray(db.notices))db=fresh()}catch{db=fresh()}
for(const m of db.members){if(seed.some(s=>s.id===m.id)&&!m.photo)m.photo=`assets/avatars/member-${m.id}.jpg`}
db.resources ??= resourceExamples();
db.favorites ??= {};
let mode='admin',query='',category='Все';const me=1;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'}),money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽',date=s=>s?new Date(s+'T12:00:00').toLocaleDateString('ru-RU'):'—';
const member=id=>db.members.find(m=>m.id===Number(id)),warnings=id=>db.notices.filter(n=>n.memberId===id&&n.kind==='warning').length;
const status=m=>({active:'В клубе',pending:'На рассмотрении',excluded:'Исключён'}[m.membership]);
const initials=s=>s.split(/\s+/).slice(0,2).map(x=>x[0]).join('');
const avatar=m=>`<div class="avatar" style="background:${esc(m.color||'#eee9fb')};color:${esc(m.ink||'#63449a')}">${m.photo?`<img src="${esc(m.photo)}" alt="">`:esc(initials(m.name))}</div>`;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function save(action){db.audit.unshift({action,date:today()});try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch{toast('Не удалось сохранить: хранилище браузера заполнено. Уменьшите фото.');return false}}
function modal(html){$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal()}
$('#close-dialog').onclick=()=>$('#dialog').close();
const routes=[['overview','◈','Обзор клуба'],['members','◎','Участники'],['profile','◉','Моя анкета'],['library','▤','Библиотека'],['rules','≡','Правила клуба'],['admin','▦','Управление'],['payments','₽','Взносы'],['notices','⚑','Замечания и штрафы']];
const adminRoutes=['admin','payments','notices'];
function route(){let r=location.hash.slice(1)||'overview';return routes.some(x=>x[0]===r)&&!(mode==='member'&&adminRoutes.includes(r))?r:'overview'}
function render(){let r=route();$('#nav').innerHTML=routes.filter(x=>mode==='admin'||!adminRoutes.includes(x[0])).map(([id,symbol,label])=>`<a href="#${id}" class="${r===id?'active':''}" ${r===id?'aria-current="page"':''}><span class="nav-icon">${icon(id)}</span><span class="nav-text">${label}</span></a>`).join('');({overview,members,profile,library,rules,admin,payments,notices}[r])();requestAnimationFrame(()=>{const active=$('#nav a.active');if(active&&innerWidth<=760)$('#nav').scrollTo({left:active.offsetLeft-20,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});updateScrollUI()})}
$('#mode').onchange=e=>{mode=e.target.value;$('#dialog').close();render()};window.onhashchange=()=>{$('#dialog').close();query='';render();scrollTo(0,0)};
const head=(eyebrow,title,sub,action='')=>`<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;
const button=(text,action,cls='primary')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>dispatch(b.dataset.action))}
function overview(){const active=db.members.filter(m=>m.membership==='active');$('#app').innerHTML=head('ВАШЕ СООБЩЕСТВО','Хорошие связи.<br>Большие возможности.','Всё, что объединяет клуб, — в одном пространстве.')+`<section class="hero"><div><span class="pill">MARKETING CLUB / ДАГЕСТАН</span><h2>Здесь знают,<br>с кем делать дело.</h2><p>Находите своих людей, обменивайтесь опытом<br>и создавайте проекты вместе.</p><a class="light-button" href="#members">Познакомиться с участниками ↗</a></div><div class="hero-art" aria-hidden="true"><div class="original-logo"><img src="club-reference.png" alt=""></div><i>В ОДНОМ КРУГУ</i></div></section><div class="stats"><a href="#members"><small>Участников в клубе</small><strong>${active.length.toString().padStart(2,'0')}</strong><span>Люди, с которыми стоит познакомиться ↗</span></a><a href="${mode==='admin'?'#admin':'#profile'}"><small>${mode==='admin'?'Заявки на вступление':'Моё участие'}</small><strong>${mode==='admin'?db.members.filter(m=>m.membership==='pending').length:status(member(me))}</strong><span>${mode==='admin'?'Ждут решения администратора':'Анкета и срок участия'} ↗</span></a><a href="#rules"><small>Участие в клубе</small><strong>4 000 <em>₽</em></strong><span>Организационный взнос за 6 месяцев ↗</span></a></div><div class="section-title"><h2>Люди клуба</h2><a href="#members">Все участники ↗</a></div><div class="cards">${active.slice(0,3).map(card).join('')}</div><section class="bottom-note"><span>01 / КУЛЬТУРА ОБЩЕНИЯ</span><h2>Только маркетинг и бизнес.<br>С уважением к каждому.</h2><a href="#rules">Наши правила ↗</a></section>`;bind()}
function card(m){return `<article class="card"><div class="person-top">${avatar(m)}<div><h3>${esc(m.name)}</h3><small>${esc(m.city)}</small></div></div><div class="role">${esc(m.role)}</div><p>${esc(m.bio)}</p><div class="tags">${m.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="card-bottom"><span class="availability">● ${esc(m.status)}</span>${button('Профиль ↗','view:'+m.id,'text-button')}</div></article>`}
function members(){ $('#app').innerHTML=head('ЗНАКОМСТВА И КОЛЛАБОРАЦИИ','Люди клуба','Найдите специалиста, партнёра или новый взгляд на свою задачу. Анкеты и портреты демонстрационные.',button('Моя анкета ↗','edit:'+me))+`<div class="toolbar"><input id="search" type="search" aria-label="Поиск участников" placeholder="Поиск по имени, городу, компании или специализации" value="${esc(query)}"><select id="category" aria-label="Специализация">${['Все','Маркетинг','Дизайн','Бизнес','Разработка','Контент'].map(c=>`<option ${category===c?'selected':''}>${c}</option>`).join('')}</select></div><div id="results"></div>`;$('#search').oninput=e=>{query=e.target.value;memberResults()};$('#category').onchange=e=>{category=e.target.value;memberResults()};memberResults();bind()}
function memberResults(){const list=db.members.filter(m=>m.membership==='active'&&(category==='Все'||m.category===category)&&[m.name,m.city,m.company,m.role,m.bio,m.help,...m.tags].join(' ').toLowerCase().includes(query.toLowerCase()));$('#results').innerHTML=`<p class="result-count">Участников: ${list.length}</p><div class="cards">${list.length?list.map(card).join(''):'<div class="empty">Никого не нашли. Попробуйте другой запрос.</div>'}</div>`;bind()}
function view(id){const m=member(id);modal(`<div class="person-top">${avatar(m)}<div><h2>${esc(m.name)}</h2><p>${esc(m.role)} · ${esc(m.city)}</p></div></div><p>${esc(m.company)}</p><div class="detail-section"><h3>О себе</h3><p>${esc(m.bio)}</p></div><div class="detail-section"><h3>Чем могу помочь</h3><p>${esc(m.help)}</p></div><div class="detail-section"><h3>Кого хочу найти</h3><p>${esc(m.seek)}</p></div>${m.social&&/^https?:\/\//.test(m.social)?`<a class="primary" href="${esc(m.social)}" target="_blank" rel="noopener noreferrer">Личный аккаунт ↗</a>`:'<p class="small-note">Контакты в тестовых анкетах не указаны.</p>'}`)}
function profile(){const m=member(me);$('#app').innerHTML=head('ЛИЧНЫЙ КАБИНЕТ','Моя анкета','В демо вы просматриваете кабинет Амины Юсуповой.',button('Редактировать анкету','edit:'+me))+`<div class="profile-layout"><div>${card(m)}</div><div class="panel"><span class="eyebrow">МОЁ УЧАСТИЕ</span><h2>${status(m)}</h2><p>Оплачено до ${date(m.paidUntil)}</p><div class="detail-section"><h3>Замечания: ${warnings(me)} из 3</h3><p>При трёх замечаниях участник подлежит исключению.</p></div><h3>Моя история</h3>${db.notices.filter(n=>n.memberId===me).map(n=>`<div class="history-item">${esc(n.reason)}<small>${date(n.date)} · ${n.kind==='fine'?money(n.amount):'Замечание'}</small></div>`).join('')||'<p>Замечаний и штрафов нет.</p>'}</div></div>`;bind()}
const ruleItems = [
  'развитие тем, не связанных с маркетингом и бизнесом то есть исключаем полностью темы политики, религии, кулинарии, спорта, авто, мотивация, различные лайфхаки, и "полезный" на ваш взгляд контент из тем, не связанных с бизнесом и маркетингом и т.д., а также просьбы сделать репост, проголосовать, помочь в благотворительности и т.д. ЕЩЕ РАЗ - тут только маркетинг и бизнес',
  'флуд, оффтоп, просто смайлики или гифки в двух сообщениях подряд, личные или бытовые вопросы не по теме, использование чата вместо гугла',
  'создание и провоцирование конфликта, оскорбление других участников, слив информации и скрина переписки в чате - удаление с чата сразу',
  'ненормативную лексику или контент;',
  'захламление чата мелкими сообщениями. Пояснение: за 3 сообщения подряд - 1 замечание',
  'Переписка 2х участников после 4-5 сообщений должна продолжаться в личке (или в диалог должен добавиться 3-й участник в течении 2-х минут);',
  'Рекламные объявления участников чата не должны быть назойливыми и должны заканчиваться призывом обращаться в личку или по контактному номеру;',
  'Не пишите ответные сообщения/реплики/ на замечания Админов по любому из этих пунктов. Есть вопросы или несогласие -переходите в личку с админом, иначе замечание!',
  'Разборы ваших кейсов, сайтов, макетов должны начинаться с заполненного брифа (образец можно запросить в личке у админов)'
];
function rules(){
  $('#app').innerHTML=head('ПРАВИЛА СООБЩЕСТВА','Правила клуба','Соблюдайте правила нашего сообщества!')+`<div class="rules-layout"><section><p class="rules-lead">Замечания могут быть за:</p>${ruleItems.map((p,i)=>`${i===5?'<h2 class="rules-important">🚫 Важно:</h2>':''}<article class="rule"><span>${i+1}</span><div><p>${esc(p)}</p></div></article>`).join('')}<div class="panel purple rules-conclusion"><p>‼️<br>За нарушение правил чата, админами делаются замечания.<br><strong>Внимание 3 замечания и вы будете удалены из чата!</strong></p></div><section class="panel admission"><h2>Вступление в клуб</h2><p>Для вступления в наш Клуб просьба предоставить следующую информацию в одном сообщении:</p><ol><li><strong>Личные данные:</strong> имя, фамилия, город, дата рождения</li><li><strong>Профессиональная деятельность:</strong> чем занимаетесь сейчас, название компании, проектов</li><li><strong>Ссылка на личный аккаунт в соцсетях:</strong> поделитесь своей страничкой</li><li><strong>Фото в деловом стиле:</strong> для внутренней картотеки чата</li><li><strong>Телефонная визитка:</strong> ваш номер телефона и как вас корректно записать</li></ol><p>✅ После получения положительного ответа о вступлении (обычно в течение 1–2 дней после предоставления информации) необходимо внести организационный взнос в размере <strong>4000 рублей за следующие 6 месяцев</strong> участия.</p><p>P.S. Будем благодарны, если напишете, как вы узнали о Клубе ?</p></section></section><aside><div class="panel purple"><h2>3 замечания —<br>удаление из чата</h2><p>По пункту 3 — удаление с чата сразу.</p></div><div class="panel"><h3>Анкета участника</h3><p>Личные данные, деятельность и контакты — в вашей анкете.</p><a class="text-button" href="#profile">Открыть мою анкету ↗</a></div><div class="panel"><h3>Объявления</h3><p>📌также присоединяйтесь к бесплатному WhatsApp-маркетинг-каналу <strong>(не чат)</strong> по ссылке:</p><a class="text-button" href="https://chat.whatsapp.com/FhTKPf1x9V12nDoPxlF4YO" target="_blank" rel="noopener noreferrer">Открыть маркетинг-канал ↗</a><p>👉🏼вся информация будет в папке «Объявления».</p></div></aside></div>`;
}
function admin(){$('#app').innerHTML=head('АДМИНИСТРАТОР','Управление клубом','Анкеты, заявки и статусы участников.',button('+ Добавить участника','new'))+`<div class="toolbar"><input id="admin-search" aria-label="Поиск в управлении" placeholder="Найти участника" value="${esc(query)}"></div><div id="admin-table"></div>`;$('#admin-search').oninput=e=>{query=e.target.value;adminTable()};adminTable();bind()}
function adminTable(){const list=db.members.filter(m=>m.name.toLowerCase().includes(query.toLowerCase()));$('#admin-table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Участник</th><th>Статус</th><th>Замечания</th><th>Участие до</th><th>Действия</th></tr></thead><tbody>${list.map(m=>`<tr><td><div class="person-top">${avatar(m)}<div><strong>${esc(m.name)}</strong><small>${esc(m.role)}</small></div></div></td><td><span class="badge ${m.membership}">${status(m)}</span></td><td><span class="${warnings(m.id)>=3?'danger':''}">${warnings(m.id)} / 3${warnings(m.id)>=3?' · Требует исключения':''}</span></td><td>${date(m.paidUntil)}</td><td><div class="actions">${button('Анкета','edit:'+m.id,'text-button')}${m.membership==='pending'?button('Одобрить','approve:'+m.id,'text-button'):''}${m.membership!=='excluded'?button('Исключить','exclude:'+m.id,'text-button danger'):button('Восстановить','restore:'+m.id,'text-button')}</div></td></tr>`).join('')||'<tr><td colspan="5">Участников не найдено</td></tr>'}</tbody></table></div>`;bind()}
function edit(id){if(mode!=='admin'&&Number(id)!==me)return;const m=id?member(id):{name:'',city:'',role:'',category:'Маркетинг',tags:[],membership:'pending'};const field=(name,label,type='text',required=false)=>`<label>${label}<input name="${name}" type="${type}" value="${esc(m[name])}" maxlength="200" ${required?'required':''}></label>`;modal(`<span class="eyebrow">АНКЕТА УЧАСТНИКА</span><h2>${id?'Редактировать профиль':'Новый участник'}</h2><form id="edit-form"><div class="form-grid">${field('name','Имя и фамилия','text',true)}${field('city','Город','text',true)}${field('birth','Дата рождения','date')}${field('role','Чем занимаетесь','text',true)}${field('company','Компания / проекты')}${field('social','Личный аккаунт (https://…)','url')}${field('phone','Номер телефона','tel')}${field('contactName','Как записать в контактах')}</div><label>Специализация<select name="category">${['Маркетинг','Дизайн','Бизнес','Разработка','Контент'].map(c=>`<option ${m.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Фото в деловом стиле (до 1 МБ)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="small-note">Телефон, дата рождения и источник знакомства видны только в своей анкете и администратору.</p>${['bio','help','seek','referral'].map((k,i)=>`<label>${['О себе','Чем можете помочь','Кого хотите найти','Как узнали о клубе?'][i]}<textarea name="${k}" maxlength="1000">${esc(m[k])}</textarea></label>`).join('')}<button class="primary" type="submit">Сохранить анкету</button></form>`);$('#edit-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data={};for(const [k,v]of f)if(k!=='photo')data[k]=v.trim();if(!data.name||!data.city||!data.role)return toast('Заполните имя, город и деятельность');if(data.social&&!/^https?:\/\//i.test(data.social))return toast('Укажите ссылку с https://');const file=f.get('photo');let photo=m.photo||'';if(file.size){if(file.size>1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('Выберите JPG, PNG или WebP до 1 МБ');photo=await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)})}const next={...m,...data,photo,id:m.id||Date.now(),tags:m.tags||[],status:m.status||'Открыт к знакомству',color:m.color||'#eee9fb',ink:m.ink||'#63449a'};if(id)db.members[db.members.findIndex(x=>x.id===m.id)]=next;else db.members.push(next);if(save('Сохранена анкета: '+next.name)){$('#dialog').close();render();toast('Анкета сохранена в этом браузере')}}}
function confirmStatus(id,next){const m=member(id);modal(`<h2>${next==='excluded'?'Исключить участника?':next==='active'?'Принять участника в клуб?':'Изменить статус?'}</h2><p>${esc(m.name)}</p><p class="detail-section">${next==='excluded'?'Анкета останется в истории администратора и исчезнет из каталога. Удалить участника из WhatsApp нужно вручную.':'Участник появится в каталоге. Взнос записывается отдельно.'}</p><form id="status-form"><label>Комментарий<textarea name="reason" required maxlength="500"></textarea></label><button class="primary" type="submit">Подтвердить</button></form>`);$('#status-form').onsubmit=e=>{e.preventDefault();m.membership=next;save(`${m.name}: ${status(m)}. ${new FormData(e.target).get('reason')}`);$('#dialog').close();render();toast('Статус обновлён')}}
let paymentQuery='';
function duesState(m){
  if(!m.paidUntil)return {rank:0,days:null,label:'Взнос не записан'};
  const days=Math.round((Date.parse(m.paidUntil+'T00:00:00Z')-Date.parse(today()+'T00:00:00Z'))/86400000);
  if(days<0)return {rank:0,days,label:`Просрочено на ${Math.abs(days)} дн.`};
  if(days===0)return {rank:1,days,label:'Срок заканчивается сегодня'};
  if(days<=14)return {rank:1,days,label:`До окончания: ${days} дн.`};
  return {rank:2,days,label:'Действует'};
}
function payments(){
  $('#app').innerHTML=head('АДМИНИСТРАТОР','Членские взносы','4 000 ₽ за шесть месяцев. Демо не принимает реальные платежи.',button('+ Записать взнос','payment'))+`
    <div class="info-strip">Сначала — просроченные и незаписанные взносы, затем сроки, заканчивающиеся в ближайшие 14 дней. Дата окончания включена в оплаченный период.</div>
    <div class="toolbar notice-toolbar"><label class="notice-search"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="payment-search" type="search" aria-label="Поиск взносов по имени" placeholder="Найти участника по имени" value="${esc(paymentQuery)}"><button id="clear-payment-search" class="text-button" type="button" aria-label="Очистить поиск взносов" ${paymentQuery?'':'hidden'}>Сбросить</button></label></div><div id="payment-results"></div>`;
  $('#payment-search').oninput=e=>{paymentQuery=e.target.value;$('#clear-payment-search').hidden=!paymentQuery;paymentResults()};
  $('#clear-payment-search').onclick=()=>{paymentQuery='';$('#payment-search').value='';$('#clear-payment-search').hidden=true;paymentResults();$('#payment-search').focus()};
  paymentResults();bind();
}
function paymentResults(){
  const q=paymentQuery.trim().toLocaleLowerCase('ru');
  const list=db.members.filter(m=>m.membership!=='excluded'&&m.name.toLocaleLowerCase('ru').includes(q)).sort((a,b)=>duesState(a).rank-duesState(b).rank||(a.paidUntil||'').localeCompare(b.paidUntil||'')||a.name.localeCompare(b.name,'ru'));
  const urgent=list.filter(m=>duesState(m).rank<2);
  $('#payment-results').innerHTML=`${urgent.length?`<div class="dues-alert" role="status">${icon('notices')}<span><strong>Требуют внимания: ${urgent.length}</strong> · Срок взноса истёк, заканчивается или ещё не записан.</span></div>`:''}<p class="result-count" aria-live="polite">Участников: ${list.length}</p><div class="table-wrap"><table><thead><tr><th>Участник</th><th>Оплачено до</th><th>Статус оплаты</th></tr></thead><tbody>${list.map(m=>{const s=duesState(m);return `<tr class="${s.rank<2?'dues-urgent':''}"><td><strong>${esc(m.name)}</strong></td><td>${date(m.paidUntil)}</td><td><span class="badge ${s.rank<2?'dues-danger':'active'}">${s.rank<2?'<span class="dues-dot" aria-hidden="true"></span>':''}${s.label}</span></td></tr>`}).join('')||'<tr><td colspan="3">Участник не найден. Попробуйте другое имя.</td></tr>'}</tbody></table></div><h2 class="section-title">История записанных взносов</h2>${db.payments.filter(p=>(member(p.memberId)?.name||'').toLocaleLowerCase('ru').includes(q)).map(p=>`<div class="history-item"><strong>${esc(member(p.memberId)?.name)}</strong><p>${money(p.amount)} · ${date(p.start)} — ${date(p.end)}</p></div>`).join('')||'<p>Записей не найдено. Начальные сроки в демо не являются реальными платежами.</p>'}`;
  updateScrollUI();
}
const memberSelect=()=>`<label>Участник<select name="memberId" required>${db.members.filter(m=>m.membership==='active').map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label>`;
function addMonths(s){const d=new Date(s+'T12:00:00'),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+6);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function payment(){modal(`<h2>Записать организационный взнос</h2><p>4 000 ₽ · 6 месяцев</p><form id="payment-form">${memberSelect()}<label>Начало периода<input type="date" name="start" value="${today()}" required></label><p class="small-note">При продлении выберите дату окончания текущего периода. Запись подтверждает ручной учёт, а не оплату через сайт.</p><button class="primary" type="submit">Записать 4 000 ₽</button></form>`);$('#payment-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=Number(f.get('memberId')),start=f.get('start'),end=addMonths(start);if(!member(id))return;if(db.payments.some(p=>p.memberId===id&&start<p.end&&end>p.start))return toast('Этот период пересекается с уже записанным взносом');db.payments.unshift({id:Date.now(),memberId:id,amount:4000,start,end});member(id).paidUntil=member(id).paidUntil>end?member(id).paidUntil:end;save('Записан взнос: '+member(id).name);$('#dialog').close();render();toast('Взнос записан')}}
let noticeQuery = '';
const violationCount = id => db.notices.filter(n => n.memberId === id).length;
function notices(){
  $('#app').innerHTML=head('АДМИНИСТРАТОР','Замечания и штрафы','Прозрачная история: причина, дата и решение администратора.',button('+ Добавить запись','notice'))+`
    <div id="removal-alerts"></div>
    <div class="info-strip">Уведомление об удалении появляется при 3 записях о замечаниях или штрафах суммарно. Оплата штрафа не снимает нарушение. Удаление из группы WhatsApp выполняется вручную.</div>
    <div class="toolbar notice-toolbar"><label class="notice-search"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="notice-search" type="search" aria-label="Поиск замечаний и штрафов" placeholder="Имя участника или причина нарушения" value="${esc(noticeQuery)}"><button id="clear-notice-search" class="text-button" type="button" aria-label="Очистить поиск" ${noticeQuery?'':'hidden'}>Сбросить</button></label></div>
    <div id="notice-results"></div>
    <h2 class="section-title">Журнал действий</h2>${db.audit.slice(0,15).map(a=>`<div class="history-item"><p>${esc(a.action)}</p><small>${date(a.date)}</small></div>`).join('')||'<p>Здесь появятся действия администратора.</p>'}`;
  $('#notice-search').oninput=e=>{noticeQuery=e.target.value;$('#clear-notice-search').hidden=!noticeQuery;noticeResults()};
  $('#clear-notice-search').onclick=()=>{noticeQuery='';$('#notice-search').value='';$('#clear-notice-search').hidden=true;noticeResults();$('#notice-search').focus()};
  const flagged=db.members.filter(m=>violationCount(m.id)>=3);
  $('#removal-alerts').innerHTML=flagged.length?`<section class="removal-alert" role="status"><div class="removal-heading">${icon('notices')}<div><h2>Пора удалить из группы WhatsApp</h2><p>Участники с тремя и более нарушениями. Проверьте удаление из группы, даже если на платформе уже стоит статус «Исключён».</p></div></div><div class="removal-members">${flagged.map(m=>`<div class="removal-member"><div><strong>${esc(m.name)}</strong><small>Нарушений: ${violationCount(m.id)} · замечаний: ${warnings(m.id)} · штрафов: ${violationCount(m.id)-warnings(m.id)}</small></div>${button('Посмотреть записи','notice-filter:'+m.id,'text-button')}</div>`).join('')}</div></section>`:'';
  noticeResults();bind();
}
function noticeResults(){
  const q=noticeQuery.trim().toLocaleLowerCase('ru');
  const list=[...db.notices].reverse().filter(n=>[member(n.memberId)?.name,n.reason].join(' ').toLocaleLowerCase('ru').includes(q));
  $('#notice-results').innerHTML=`<p class="result-count" aria-live="polite">Найдено записей: ${list.length}</p><div class="table-wrap"><table><thead><tr><th>Участник / дата</th><th>Причина</th><th>Тип</th><th>Сумма / статус</th></tr></thead><tbody>${list.map(n=>`<tr><td><strong>${esc(member(n.memberId)?.name)}</strong><small>${date(n.date)}</small>${violationCount(n.memberId)>=3?'<span class="removal-badge">Пора удалить из группы</span>':''}</td><td>${esc(n.reason)}</td><td>${n.kind==='fine'?'Денежный штраф':'Замечание'}</td><td>${n.kind==='fine'?money(n.amount)+(n.paid?' · Оплачен':button('Отметить оплату','fine-paid:'+n.id,'text-button')):`${warnings(n.memberId)} / 3`}</td></tr>`).join('')||'<tr><td colspan="4"><div class="notice-empty">Записей не найдено. Попробуйте другое имя или причину.</div></td></tr>'}</tbody></table></div>`;
  bind();
}
function notice(){modal(`<h2>Новая запись</h2><form id="notice-form">${memberSelect()}<label>Тип<select name="kind" id="notice-kind"><option value="warning">Замечание</option><option value="fine">Денежный штраф</option><option value="exclusion">Немедленное исключение · пункт 3</option></select></label><label>Причина<textarea name="reason" required maxlength="500"></textarea></label><label>Дата<input type="date" name="date" value="${today()}" max="${today()}" required></label><label id="amount-label" hidden>Сумма штрафа, ₽<input name="amount" type="number" min="1" max="1000000" step="1"></label><p class="small-note" id="notice-hint">При третьем замечании статус участника будет изменён на «Исключён». Удаление из WhatsApp — вручную.</p><button class="primary" type="submit">Сохранить запись</button></form>`);$('#notice-kind').onchange=e=>{$('#amount-label').hidden=e.target.value!=='fine';$('#amount-label input').required=e.target.value==='fine'};$('#notice-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=Number(f.get('memberId')),m=member(id),kind=f.get('kind'),reason=f.get('reason').trim();if(!m||!reason)return;db.notices.push({id:Date.now(),memberId:id,kind:kind==='exclusion'?'warning':kind,reason,date:f.get('date'),amount:kind==='fine'?Number(f.get('amount')):0,paid:false});if(kind==='exclusion'||warnings(id)>=3)m.membership='excluded';save('Добавлена запись: '+m.name+' — '+reason);$('#dialog').close();render();toast(m.membership==='excluded'?'Участник исключён на платформе. Обновите WhatsApp вручную.':'Запись сохранена')}}
function dispatch(a){const [type,id]=a.split(':');if(type==='view')return view(id);if(type==='edit')return edit(id);if(type==='resource-view')return resourceView(id);if(type==='favorite')return toggleFavorite(id);if(mode!=='admin')return;if(type==='notice-filter'){noticeQuery=member(id)?.name||'';notices();$('#notice-search').focus();return}if(type==='resource-new')return resourceEdit();if(type==='resource-edit')return resourceEdit(id);if(type==='resource-delete')return resourceDelete(id);({new:()=>edit(),exclude:()=>confirmStatus(id,'excluded'),approve:()=>confirmStatus(id,'active'),restore:()=>confirmStatus(id,'active'),payment,notice,'fine-paid':()=>{const n=db.notices.find(n=>n.id===Number(id));if(n){n.paid=true;save('Оплата штрафа: '+member(n.memberId).name);render();toast('Оплата отмечена')}}}[type])?.()}
render();
